#!/bin/bash

function menu_print() {

  echo -e "what do you wan't to do ?"
  echo -e "    1.Install TightVNCServer"
  echo -e "    2.Copy files in NetworkManager"
  echo -e "    3.Install kalipi-config"
  echo -e "    4.Configure SSH server port"

  nb_choice="4"
}

function menu_ask() {

  nb_choice_print="$(seq 1 1 $nb_choice)"
  
  read -p "make a choice (`echo -n $nb_choice_print` or q to quit) : " -n 1 choice_menu
  echo ""
}

function menu_ask_check() {

  choice_menu=$(echo $choice_menu | tr '[A-Z]' '[a-z]')

  if [[ "$choice_menu" == 'q' ]]; then

    echo "Have a nice day ;) .."
    sleep 0.5
    exit 255
  fi

  if [[ "$choice_menu" < "1" ]] || [[ "$choice_menu" > "$nb_choice" ]]; then
    
    echo -e "Make a better choice .."
    sleep 1.2
  else
    
    loop_menu=false
  fi
}

function menu_ask_loader() {
  
    if [[ "$choice_menu" -eq "1" ]]; then
    echo -e "You choose 1"
    ./install_tightvnc
  
  elif [[ "$choice_menu" -eq "2" ]]; then
    echo -e "You choose 2"
    ./install_connection

  elif [[ "$choice_menu" -eq "3" ]]; then
    echo -e "You choose 3"
    ./install_kalipi_config
    
  elif [[ "$choice_menu" -eq "4" ]]; then
    echo -e "You choose 4"
    ./install_sshd

  else
    echo -e "trouble here .. contact dev for furthere info"
    exit 2
  fi
}

loop_menu=true

while $loop_menu; do
  clear
  menu_print
  menu_ask
  menu_ask_check
done
menu_ask_loader
