#!/bin/bash

function configure_sshd_port() {
  
  loop_ssh_port_confirm=true

  while $loop_ssh_port_confirm; do

    echo -e "Current port is $current_port"
  
    read -p "Do you wan't to change it ? (y/n) " -n 1 confirm_ssh_port
    echo ""

    confirm_ssh_port=$(echo $confirm_ssh_port | tr '[A-Z]' '[a-z]')

    if [[ "$confirm_ssh_port" == "y" ]]; then
      loop_ssh_port_confirm=false
    
    elif [[ "$confirm_ssh_port" == "n" ]]; then
      echo -e "Have a nice day ;) .."
      sleep 0.5
      exit 255 
    
    else
      echo -e "Make a better choice .."
      sleep 1.2

    fi
  done

  loop_ssh_port_choice=true

  while $loop_ssh_port_choice; do
    current_port=$(grep "Port " sshd_config | cut -d" " -f2)

    echo -e "Current port : ${current_port}"

    read -p "Enter a port : " choice_ssh_port

    if ! [[ "$choice_ssh_port" =~ ^[0-9]+$ ]]; then
      echo "Enter a number"

    elif [[ "$choice_ssh_port" -lt "1" ]] || [[ "$choice_ssh_port" -gt "65535" ]]; then
      echo "enter a number in the good range"

    else 
      loop_ssh_port_choice=false
      
    fi
  done
  
}

configure_sshd_port
