#!/bin/bash 

function install_tightvnc_service() {
  
  cp ./TightVNCServer/tightvncserver.service /etc/systemd/system/
  chown root:root /etc/systemd/system/tightvncserver.service
  chmod 755 /etc/systemd/system/tightvncserver.service
  systemctl enable tightvncserver.service
}

if [[ ! -f "/usr/bin/tightvncserver" ]]; then

  apt install tightvncserver
fi

if [[ ! -f "~/.vnc/passwd" ]]; then

  tightvncserver
fi

install_tightvnc_service