#!/bin/bash 

function install_tightvnc_service() {
  
  sudo cp ./TightVNCServer/tightvncserver.service /etc/systemd/system/
  sudo chown root:root /etc/systemd/system/tightvncserver.service
  sudo chmod 755 /etc/systemd/system/tightvncserver.service
  sudo systemctl enable tightvncserver.service
}

if [[ ! -f "/usr/bin/tightvncserver" ]]; then

  sudo apt install tightvncserver
fi

if [[ ! -f "~/.vnc/passwd" ]]; then

  tightvncserver
fi

install_tightvnc_service