#!/bin/bash

function check_root() {
	if [ "$UID" -ne 0 ]; then
		echo "run script as root."
		sleep 2
		exit 1
	fi	
}

function user_ask() {
	read -p "Enter an user name to create : " username_brut
}

function user_check() {
	username_first=$(echo ${username_brut::1} | tr '[A-Z]' '[a-z]')
	username_clean=$(echo "${username_first}${username_brut:1}")
}

function user_add() {
	adduser $username_clean
}

function user_group_grep() {
	id_user=$(id $SUDO_USER | cut -d"," -f2- | sed 's/,/\n/g' | cut -d"(" -f2- | cut -d")" -f-1)	
}

function user_group_add() {
	usermod -aG $(echo $(echo ${id_user} | sed 's/ /,/g') $(echo ${username_clean}))
}

function user_group() {
	user_group_grep
	user_group_add
}

function main() {
	check_root
	user_ask
	user_check
	user_add
	user_group
}

main
