#!/bin/bash 
# Bash Color
green='\e[32m'
red='\e[31m'
yellow='\e[33m'
blue='\e[34m'
lgreen='\e[92m'
lyellow='\e[93m'
lblue='\e[94m'
lmagenta='\e[95m'
lcyan='\e[96m'
blink_red='\033[05;31m'
restore='\033[0m'
reset='\e[0m'

function warning() {
  printf "${red}[ WARNING  ]${reset} $*${reset}\n"
  sleep 1.5
}

function question() {
  printf "${green}[ QUESTION ]${reset} $*${reset}\n"
}

function answer() {
  printf "${lgreen}[${reset}$1${lgreen}]${reset}$2${reset}\n"
}

function info() {
  printf "${yellow}[   INFO   ]${reset} $*${reset}\n"
}

function prompt() {
  printf "${blue}[ WAITING..]: ${reset}"
}

function root_check() {
  if [[ "$EUID" -ne "0" ]];then
    warning "Scripts must be run as root."
    exit 1
  fi
}

function print_color() {
  printf "${green}green${reset}\n${red}red${reset}\n${yellow}yellow${reset}\n${blue}blue${reset}\n${lgreen}lgreen${reset}\n${lyellow}lyellow${reset}\n${lblue}lblue${reset}\n${lmagenta}lmagenta${reset}\n${lcyan}lcyan${reset}\n${blink_red}blink_red${reset}\n"
}

function print() {
  for i in $1
}

function choice() {
  local nb_choice=$1
  check="0"
  
  prompt
  read

  REPLY=${REPLY:0:1}
  REPLY=`echo $REPLY | tr '[A-Z]' '[a-z]'`

  if [[ "$REPLY" == q ]]; then
    info "Good Bye"
    exit 1
  elif [[ "$REPLY" < 1 ]] || [[ "$REPLY" > "$nb_choice" ]]; then
    warning "Wrong Choice"
  else
    check="1"
    return ${REPLY}
  fi
}

function main_menu() {
  main_menu_print=(
    "Install TightVNCServer"
    "Copy files in NetworkManager"
    "Install kalipi-config"
    "Configure SSH server port"
  )
  main_menu_nb_choice="4"
}

function loop() {
  while $loop; do
    `echo $1`
    choice $2
    return_code=$?
    if [[ "$check" == "1" ]]; then
      return ${return_code}
    fi
  done
}

function main() {
  #root_check
  #print_color

  loop "main_menu" "${main_menu_nb_choice}"
  echo $?
}

main